language: java
jdk:
  - oraclejdk8
services:
  - mysql
before_script:
  - ./.travis/.initialize.db.sh;
script: 
  - mvn test
  - mvn -U package
notifications:
  slack: ivh11b4a:3wk2xOsXW1eab9RpRk2JJbyp